#!/usr/bin/env python3
"""Compile per-category exemplar files into the main exemplars.toml.

Reads exemplars_<category>.toml files, deduplicates within each category,
and writes the merged result to exemplars.toml.

Usage:
    python3 scripts/compile-exemplars.py
"""

import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # Python < 3.11

SCRIPT_DIR = Path(__file__).parent
OUTPUT = SCRIPT_DIR / "exemplars.toml"

CATEGORIES = [
    "needs_memory",
    "needs_code",
    "needs_both",
    "no_context",
]

HEADER = """\
# Bootstrap exemplars for the semantic classifier.
#
# AUTO-GENERATED by compile-exemplars.py
# Do not edit this file directly. Instead edit the per-category files:
#   exemplars_needs_context_project.toml
#   exemplars_needs_context_generic.toml
#   exemplars_no_context_project.toml
#   exemplars_no_context_generic.toml
#
# Then run: python3 scripts/compile-exemplars.py
#
# This file is the quality gate. Project and global exemplars
# are validated against these before being accepted.
#
# Do not modify this file for per-project tuning. Instead:
#   - <project>/.claude/context/exemplars.toml  (project-specific)
#   - ~/.claude/context/exemplars.toml          (global)

"""


def load_category(category: str) -> list[str]:
    path = SCRIPT_DIR / f"exemplars_{category}.toml"
    if not path.exists():
        print(f"WARNING: {path.name} not found, skipping", file=sys.stderr)
        return []
    with open(path, "rb") as f:
        data = tomllib.load(f)
    examples = data.get(category, {}).get("examples", [])
    return examples


def deduplicate(examples: list[str]) -> list[str]:
    seen = set()
    result = []
    for ex in examples:
        key = ex.strip().lower()
        if key not in seen:
            seen.add(key)
            result.append(ex)
    return result


def escape_toml_string(s: str) -> str:
    """Escape a string for TOML double-quoted format."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    total = 0
    dupes_total = 0
    lines = [HEADER]

    for category in CATEGORIES:
        raw = load_category(category)
        deduped = deduplicate(raw)
        dupes = len(raw) - len(deduped)
        total += len(deduped)
        dupes_total += dupes

        print(
            f"{category}: {len(deduped)} exemplars ({dupes} duplicates removed)",
            file=sys.stderr,
        )

        lines.append(f"[{category}]")
        lines.append("examples = [")
        for ex in deduped:
            lines.append(f'    "{escape_toml_string(ex)}",')
        lines.append("]")
        lines.append("")

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines))

    print(f"---", file=sys.stderr)
    print(
        f"Total: {total} exemplars ({dupes_total} duplicates removed)", file=sys.stderr
    )
    print(f"Written to {OUTPUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
